refactor: update sh error trap

diff --git a/images/dockerfile b/images/dockerfile
--- a/images/dockerfile
+++ b/images/dockerfile
@@ -10,13 +10,13 @@ ADD . /tmp/setup
 
 WORKDIR /var/local
 
-ENTRYPOINT [ "/usr/bin/env", "bash", "-l" ]
+ENTRYPOINT ["/usr/bin/env", "bash", "-l"]
 
 RUN <<EOF
 #!/usr/bin/env bash
 
 set -Eeuo pipefail
-trap 'echo -e "⚠  Error ($0:$LINENO): $(sed -n "${LINENO}p" "$0" 2> /dev/null | grep -oE "\S.*\S|\S" || true)" >&2; return 3 2> /dev/null || exit 3' ERR
+trap 'echo "⚠  Error ($0:$LINENO): $BASH_COMMAND" && return 3 2> /dev/null || exit 3' ERR
 
 # update
 apt-get update
@@ -37,5 +37,4 @@ apt-get install -y \
     cmake \
     libssl-dev \
     gpg
-
 EOF
