fix: fix dockerfile errors handler

diff --git a/images/dockerfile b/images/dockerfile
--- a/images/dockerfile
+++ b/images/dockerfile
@@ -15,6 +15,9 @@ ENTRYPOINT [ "/usr/bin/env", "bash", "-l" ]
 RUN <<EOF
 #!/usr/bin/env bash
 
+set -Eeuo pipefail
+trap 'echo -e "⚠  Error ($0:$LINENO): $(sed -n "${LINENO}p" "$0" 2> /dev/null | grep -oE "\S.*\S|\S" || true)" >&2; return 3 2> /dev/null || exit 3' ERR
+
 # update
 apt-get update
 apt-get install -y \
